### ISSUE TITLE
[Bug]: Garmin Sync fails with "Permission denied: 'mock_data'"

### ISSUE THREAD

**Issue by manuelkappler** [CodeWithCJ/SparkyFitness#353]
> I was able to input MFA, but sync fails:
> 
> ```
> ERROR:main:Unexpected error retrieving health and wellness data: [Errno 13] Permission denied: 'mock_data'
> INFO:     192.168.144.13:48654 - "POST /data/health_and_wellness HTTP/1.1" 500 Internal Server Error
> ``` 

 _Originally posted by @thehijacker in [#350](https://github.com/CodeWithCJ/SparkyFitness/issues/350#issuecomment-3545097845)_

I can confirm the problem, it seems to be related to the mock_data directory not existing, but I haven't found out where to create the directory. I'm also not sure whether it is intended behavior that it tries to save the data locally despite the data source being set to 'garmin', perhaps @CodeWithCJ could elaborate on that? 

(https://github.com/CodeWithCJ/SparkyFitness/blob/05be97ea91e2f717c1a8b2e923c911fa15b31862/SparkyFitnessGarmin/main.py#L709)

**Comment by FMeinicke** [comment]
I'm experiencing the same bug after updating to v0.15.9.3.

As a workaround, you can manually create the missing directory with correct ownership (the main process runs as the `daemon` user, thus, this user must be able to write into this directory):

```console
docker-host:/path/to/sparkyfitness$ docker compose exec -u root sparkyfitness-garmin bash
root@4840c44d1c09:/app# mkdir mock_data
root@4840c44d1c09:/app# chown daemon: mock_data
root@4840c44d1c09:/app# ls -al
total 19
drwxr-xr-x 1 root   root       3 Nov 18 10:25 .
drwxr-xr-x 1 root   root       4 Nov 18 10:06 ..
-rw-r--r-- 1 root   root   51722 Nov 18 02:02 main.py
drwxr-xr-x 2 daemon daemon     2 Nov 18 10:25 mock_data
-rw-r--r-- 1 root   root      94 Nov 18 02:02 requirements.txt
root@4840c44d1c09:/app# logout
docker-host:/path/to/sparkyfitness$ docker compose restart sparkyfitness-garmin
```

where `/path/to/sparkyfitness` is the directory containing the `docker-compose.yml` file of the stack.

After that, and re-triggering an update of the data provider, the data is successfully synced and stored in the `mock_data` directory.  
As I said, this is only a workaround until the actual issue of the missing (or incorrect?) directory is fixed.

**Comment by thehijacker** [comment]
This workaround works. But I also have this in logs every full hour:

`[2025-11-18T16:00:00.031Z] [ERROR] Error during scheduled Garmin data sync: garminConnectService.getGarminDailySummary is not a function`

**Comment by CodeWithCJ** [comment]
Issue with mock_data is resolved. Give it a try.
